name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - uses: actions/checkout@v2
      # Step 2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # Step 3
      - name: Install dependencies
        run: pip install -r requirements.txt
      # Step 4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      # Step 5
      - name: Build Application and Run unit Test
        run: nohup python3 manage.py runserver 0.0.0.0:7000 &

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        #Remember the secrets we embedded? this is how we access them
        aws_access_key: ${{ secrets.Actions.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.Actions.AWS_SECRET_ACCESS_KEY }}
        
        #Replace the values here with your names you submitted in one of 
        #The previous sections
        application_name: rami
        environment_name: Rami-env
        
        #The version number could be anything. You can find a dynamic way 
        #Of doing this.
        version_label: 12348
        region: "us-east-2"
        deployment_package: deploy.zip